CREATE TABLE category (
    id SERIAL PRIMARY KEY,
    name VARCHAR(255) DEFAULT '',
    image TEXT DEFAULT '',
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP
);
